import { MappedGroupDictionary } from "@/types";

export type ServiceLanguageLibrary = (string | string[])[][];

export const azureLanguages: MappedGroupDictionary = {
  "Afrikaans": [["af-ZA"]],
  "Albanian": [["sq-AL"]],
  "Amharic": [["am-ET"]],

  "Arabic": [
    ["ar-DZ", "Algeria"],
    ["ar-BH", "Bahrain), modern standard"],
    ["ar-EG", "Egypt"],
    ["ar-IQ", "Iraq"],
    ["ar-IL", "Israel"],
    ["ar-JO", "Jordan"],
    ["ar-KW", "Kuwait"],
    ["ar-LB", "Lebanon"],
    ["ar-LY", "Libya"],
    ["ar-MA", "Morocco"],
    ["ar-OM", "Oman"],
    ["ar-PS", "Palestinian Authority"],
    ["ar-QA", "Qatar"],
    ["ar-SA", "Saudi Arabia"],
    ["ar-SY", "Syria"],
    ["ar-TN", "Tunisia"],
    ["ar-AE", "United Arab Emirates"],
    ["ar-YE", "Yemen"],
  ],

  "Armenian": [["hy-AM"]],
  "Azerbaijani": [["az-AZ"]],
  "Basque": [["eu-ES"]],
  "Bengali": [["bn-IN"]],
  "Bosnian": [["bs-BA"]],
  "Bulgarian": [["bg-BG"]],
  "Burmese": [["my-MM"]],
  "Catalan": [["ca-ES"]],

  "Chinese": [
    ["yue-CN", "Cantonese, Simplified"],
    ["zh-HK", "Cantonese, Traditional"],
    ["zh-CN", "Mandarin, Simplified"],
    ["zh-CN-sichuan", "Southwestern Mandarin, Simplified"],
    ["zh-TW", "Taiwanese Mandarin, Traditional"],
    ["wuu-CN", "Wu, Simplified"],
  ],

  "Croatian": [["hr-HR"]],
  "Czech": [["cs-CZ"]],
  "Danish": [["da-DK"]],

  "Dutch": [
    ["nl-BE", "Belgium"],
    ["nl-NL", "Netherlands"]
  ],

  "English": [
    ["en-AU", "Australia"],
    ["en-CA", "Canada"],
    ["en-GH", "Ghana"],
    ["en-HK", "Hong Kong"],
    ["en-IN", "India"],
    ["en-IE", "Ireland"],
    ["en-KE", "Kenya"],
    ["en-NZ", "New Zealand"],
    ["en-NG", "Nigeria"],
    ["en-PH", "Philippines"],
    ["en-SG", "Singapore"],
    ["en-ZA", "South Africa"],
    ["en-TZ", "Tanzania"],
    ["en-GB", "United Kingdom"],
    ["en-US", "United States"],
  ],

  "Estonian": [["et-EE"]],
  "Filipino": [["fil-PH"]],
  "Finnish": [["fi-FI"]],

  "French": [
    ["fr-BE", "Belgium"],
    ["fr-CA", "Canada"],
    ["fr-FR", "France"],
    ["fr-CH", "Switzerland"],
  ],

  "Galician": [["gl-ES"]],
  "Georgian": [["ka-GE"]],

  "German": [
    ["de-AT", "Austria"],
    ["de-DE", "Germany"],
    ["de-CH", "Switzerland"],
  ],

  "Greek": [["el-GR"]],
  "Gujarati": [["gu-IN"]],
  "Hebrew": [["he-IL"]],
  "Hindi": [["hi-IN"]],
  "Hungarian": [["hu-HU"]],
  "Icelandic": [["is-IS"]],
  "Indonesian": [["id-ID"]],
  "Irish": [["ga-IE"]],

  "Italian": [
    ["it-IT", "Italy"],
    ["it-CH", "Switzerland"]
  ],

  "Japanese": [["ja-JP"]],
  "Javanese": [["jv-ID"]],
  "Kannada": [["kn-IN"]],
  "Kazakh": [["kk-KZ"]],
  "Khmer": [["km-KH"]],
  "Korean": [["ko-KR"]],
  "Lao": [["lo-LA"]],
  "Latvian": [["lv-LV"]],
  "Lithuanian": [["lt-LT"]],
  "Macedonian": [["mk-MK"]],
  "Malay": [["ms-MY"]],
  "Maltese": [["mt-MT"]],
  "Marathi": [["mr-IN"]],
  "Mongolian": [["mn-MN"]],
  "Nepali": [["ne-NP"]],
  "Norwegian": [["nb-NO"]],
  "Pashto": [["ps-AF"]],
  "Persian": [["fa-IR"]],
  "Polish": [["pl-PL"]],
  "Portuguese": [["pt-BR"], ["pt-PT"]],
  "Romanian": [["ro-RO"]],
  "Russian": [["ru-RU"]],
  "Serbian": [["sr-RS"]],
  "Sinhala": [["si-LK"]],
  "Slovak": [["sk-SK"]],
  "Slovenian": [["sl-SI"]],
  "Somali": [["so-SO"]],

  "Spanish": [
    ["es-AR", "Argentina"],
    ["es-BO", "Bolivia"],
    ["es-CL", "Chile"],
    ["es-CO", "Colombia"],
    ["es-CR", "Costa Rica"],
    ["es-CU", "Cuba"],
    ["es-DO", "Dominican Republic"],
    ["es-EC", "Ecuador"],
    ["es-SV", "El Salvador"],
    ["es-GQ", "Equatorial Guinea"],
    ["es-GT", "Guatemala"],
    ["es-HN", "Honduras"],
    ["es-MX", "Mexico"],
    ["es-NI", "Nicaragua"],
    ["es-PA", "Panama"],
    ["es-PY", "Paraguay"],
    ["es-PE", "Peru"],
    ["es-PR", "Puerto Rico"],
    ["es-ES", "Spain"],
    ["es-UY", "Uruguay"],
    ["es-US", "USA"],
    ["es-VE", "Venezuela"],
  ],

  "Swahili": [
    ["sw-KE", "Kenya"],
    ["sw-TZ", "Tanzania"]
  ],

  "Swedish": [["sv-SE"]],
  "Tamil": [["ta-IN"]],
  "Telugu": [["te-IN"]],
  "Thai": [["th-TH"]],
  "Turkish": [["tr-TR"]],
  "Ukrainian": [["uk-UA"]],
  "Uzbek": [["uz-UZ"]],
  "Vietnamese": [["vi-VN"]],
  "Welsh": [["cy-GB"]],
  "Zulu": [["zu-ZA"]],
};

export const webspeechapiLangs: MappedGroupDictionary = {
  "Afrikaans": [["af-ZA"]],
  "አማርኛ": [["am-ET"]],
  "Azərbaycanca": [["az-AZ"]],
  "বাংলা": [
    // ["bn-BD", "বাংলাদেশ"], 
    ["bn-IN", "ভারত"]
  ],
  "Bahasa Indonesia": [["id-ID"]],
  "Bahasa Melayu": [["ms-MY"]],
  "Català": [["ca-ES"]],
  "Čeština": [["cs-CZ"]],
  "Dansk": [["da-DK"]],
  "Deutsch": [["de-DE"]],
  "English": [
    ["en-AU", "Australia"],
    ["en-CA", "Canada"],
    ["en-IN", "India"],
    ["en-KE", "Kenya"],
    ["en-TZ", "Tanzania"],
    ["en-GH", "Ghana"],
    ["en-NZ", "New Zealand"],
    ["en-NG", "Nigeria"],
    ["en-ZA", "South Africa"],
    ["en-PH", "Philippines"],
    ["en-GB", "United Kingdom"],
    ["en-US", "United States"],
  ],
  "Español": [
    ["es-AR", "Argentina"],
    ["es-BO", "Bolivia"],
    ["es-CL", "Chile"],
    ["es-CO", "Colombia"],
    ["es-CR", "Costa Rica"],
    ["es-EC", "Ecuador"],
    ["es-SV", "El Salvador"],
    ["es-ES", "España"],
    ["es-US", "Estados Unidos"],
    ["es-GT", "Guatemala"],
    ["es-HN", "Honduras"],
    ["es-MX", "México"],
    ["es-NI", "Nicaragua"],
    ["es-PA", "Panamá"],
    ["es-PY", "Paraguay"],
    ["es-PE", "Perú"],
    ["es-PR", "Puerto Rico"],
    ["es-DO", "República Dominicana"],
    ["es-UY", "Uruguay"],
    ["es-VE", "Venezuela"],
  ],
  "Euskara":[["eu-ES"]],
  "Filipino":[["fil-PH"]],
  "Français":[["fr-FR"]],
  "Basa Jawa":[["jv-ID"]],
  "Galego":[["gl-ES"]],
  // "ગુજરાતી":[["gu-IN"]],
  "Hrvatski":[["hr-HR"]],
  "IsiZulu":[["zu-ZA"]],
  "Íslenska":[["is-IS"]],
  "Italiano":[["it-IT", "Italia"], ["it-CH", "Svizzera"]],
  "ಕನ್ನಡ":[["kn-IN"]],
  "ភាសាខ្មែរ":[["km-KH"]],
  "Latviešu":[["lv-LV"]],
  "Lietuvių":[["lt-LT"]],
  "മലയാളം":[["ml-IN"]],
  "मराठी":[["mr-IN"]],
  "Magyar":[["hu-HU"]],
  "ລາວ":[["lo-LA"]],
  "Nederlands":[["nl-NL"]],
  "नेपाली भाषा":[["ne-NP"]],
  "Norsk bokmål":[["nb-NO"]],
  "Polski":[["pl-PL"]],
  "Português":[["pt-BR", "Brasil"], ["pt-PT", "Portugal"]],
  "Română":[["ro-RO"]],
  "සිංහල":[["si-LK"]],
  "Slovenščina":[["sl-SI"]],
  // "Basa Sunda":[["su-ID"]],
  "Slovenčina":[["sk-SK"]],
  "Suomi":[["fi-FI"]],
  "Svenska":[["sv-SE"]],
  "Kiswahili":[["sw-TZ", "Tanzania"], ["sw-KE", "Kenya"]],
  "ქართული":[["ka-GE"]],
  "Հայերեն":[["hy-AM"]],
  "தமிழ்": [
    ["ta-IN", "இந்தியா"],
    // ["ta-SG", "சிங்கப்பூர்"],
    // ["ta-LK", "இலங்கை"],
    // ["ta-MY", "மலேசியா"],
  ],
  "తెలుగు":[["te-IN"]],
  "Tiếng Việt":[["vi-VN"]],
  "Türkçe":[["tr-TR"]],
  // "اُردُو":[["ur", "پاکستان"], ["ur-IN", "بھارت"]],
  "Ελληνικά":[["el-GR"]],
  "български":[["bg-BG"]],
  "Pусский":[["ru-RU"]],
  "Српски":[["sr-RS"]],
  "Українська":[["uk-UA"]],
  "한국어":[["ko-KR"]],
  "中文": [
    ["cmn-Hans-CN", "普通话 (中国大陆)"],
    // ["cmn-Hans-HK", "普通话 (香港)"],
    ["cmn-Hant-TW", "中文 (台灣)"],
    // ["yue-Hant-HK", "粵語 (香港)"],
  ],
  "日本語":[["ja-JP"]],
  "हिन्दी":[["hi-IN"]],
  "ภาษาไทย":[["th-TH"]],
};

export const deepGramLangs: MappedGroupDictionary = {
  "English": [
    ["en-AU", "Australia"],
    ["en-GB", "United Kingdom"],
    ["en-IN", "India"],
    ["en-NZ", "New Zealand"],
    ["en-US", "United States"],
  ],
  "Chinese": [["zn-CN", "China"], ["zn-TW", "Taiwan"]],
  "Dutch": [["nl"]],
  "Flemish": [["nl"]],
  "French": [["fr", "France"], ["fr-CA", "Canada"]],
  "German": [["de"]],
  "Hindi": [["hi"]],
  "Indonesian": [["id"]],
  "Italian": [["it"]],
  "Japanese": [["ja"]],
  "Korean": [["ko"]],
  "Norwegian": [["no"]],
  "Polish": [["pl"]],
  "Portuguese": [
    ["pt-BR", "Brazil"],
    ["pt-PT", "Portugal"],
  ],
  "Russian": [["ru"]],
  "Spanish": [["es"]],
  "Swedish": [["sv"]],
  "Turkish": [["tr"]],
  "Ukrainian": [["uk"]],
};

export const whisperLangs: MappedGroupDictionary = {
  "Auto": [["auto"]],
  "Afrikaans": [["af"]],
  "Albanian": [["sq"]],
  "Amharic": [["am"]],
  "Arabic": [["ar"]],
  "Armenian": [["hy"]],
  "Assamese": [["as"]],
  "Azerbaijani": [["az"]],
  "Bashkir": [["ba"]],
  "Basque": [["eu"]],
  "Belarusian": [["be"]],
  "Bengali": [["bn"]],
  "Bosnian": [["bs"]],
  "Breton": [["br"]],
  "Bulgarian": [["bg"]],
  "Cantonese": [["yue"]],
  "Catalan": [["ca"]],
  "Chinese": [["zh"]],
  "Croatian": [["hr"]],
  "Czech": [["cs"]],
  "Danish": [["da"]],
  "Dutch": [["nl"]],
  "English": [["en"]],
  "Estonian": [["et"]],
  "Faroese": [["fo"]],
  "Finnish": [["fi"]],
  "French": [["fr"]],
  "Galician": [["gl"]],
  "Georgian": [["ka"]],
  "German": [["de"]],
  "Greek": [["el"]],
  "Gujarati": [["gu"]],
  "Haitian creole": [["ht"]],
  "Hausa": [["ha"]],
  "Hawaiian": [["haw"]],
  "Hebrew": [["he"]],
  "Hindi": [["hi"]],
  "Hungarian": [["hu"]],
  "Icelandic": [["is"]],
  "Indonesian": [["id"]],
  "Italian": [["it"]],
  "Japanese": [["ja"]],
  "Javanese": [["jw"]],
  "Kannada": [["kn"]],
  "Kazakh": [["kk"]],
  "Khmer": [["km"]],
  "Korean": [["ko"]],
  "Lao": [["lo"]],
  "Latin": [["la"]],
  "Latvian": [["lv"]],
  "Lingala": [["ln"]],
  "Lithuanian": [["lt"]],
  "Luxembourgish": [["lb"]],
  "Macedonian": [["mk"]],
  "Malagasy": [["mg"]],
  "Malay": [["ms"]],
  "Malayalam": [["ml"]],
  "Maltese": [["mt"]],
  "Maori": [["mi"]],
  "Marathi": [["mr"]],
  "Mongolian": [["mn"]],
  "Myanmar": [["my"]],
  "Nepali": [["ne"]],
  "Norwegian": [["no"]],
  "Nynorsk": [["nn"]],
  "Occitan": [["oc"]],
  "Pashto": [["ps"]],
  "Persian": [["fa"]],
  "Polish": [["pl"]],
  "Portuguese": [["pt"]],
  "Punjabi": [["pa"]],
  "Romanian": [["ro"]],
  "Russian": [["ru"]],
  "Sanskrit": [["sa"]],
  "Serbian": [["sr"]],
  "Shona": [["sn"]],
  "Sindhi": [["sd"]],
  "Sinhala": [["si"]],
  "Slovak": [["sk"]],
  "Slovenian": [["sl"]],
  "Somali": [["so"]],
  "Spanish": [["es"]],
  "Sundanese": [["su"]],
  "Swahili": [["sw"]],
  "Swedish": [["sv"]],
  "Tagalog": [["tl"]],
  "Tajik": [["tg"]],
  "Tamil": [["ta"]],
  "Tatar": [["tt"]],
  "Telugu": [["te"]],
  "Thai": [["th"]],
  "Tibetan": [["bo"]],
  "Turkish": [["tr"]],
  "Turkmen": [["tk"]],
  "Ukrainian": [["uk"]],
  "Urdu": [["ur"]],
  "Uzbek": [["uz"]],
  "Vietnamese": [["vi"]],
  "Welsh": [["cy"]],
  "Yiddish": [["yi"]],
  "Yoruba": [["yo"]]
}
